#!/usr/bin/env bash
#
# make_mac_app.sh — build a macOS "Red.app" launcher icon (the macOS analog of
# the Linux .desktop shortcut created by install.sh / dev-link.sh).
#
# Like dev-link.sh, the app points at the LIVE build output
# (release/red), so a plain rebuild (`cmake --build release -j`) updates the
# icon's target automatically — no copy, no drift. Double-clicking Red.app does
# exactly what running ./release/red from the release folder does: the launcher
# cd's into release/ and exec's the same binary with the same environment. (red
# resolves fonts/models/ini relative to its own executable path, and its dylibs
# use absolute rpaths, so the working directory doesn't actually matter — but we
# cd anyway for exact parity.)
#
# Usage:
#   ./make_mac_app.sh              # create ~/Desktop/Red.app
#   ./make_mac_app.sh /Applications   # or install to /Applications, ~/Applications, etc.
set -euo pipefail

SRC_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BIN="$SRC_DIR/release/red"
ICON_SRC="$SRC_DIR/icon.png"
DEST_DIR="${1:-$HOME/Desktop}"
APP="$DEST_DIR/Red.app"

[[ -x "$BIN" ]]      || { echo "ERROR: $BIN not found/executable. Build first: cmake --build \"$SRC_DIR/release\" -j"; exit 1; }
[[ -f "$ICON_SRC" ]] || { echo "ERROR: $ICON_SRC not found"; exit 1; }

echo "[*] Building $APP  ->  $BIN"
rm -rf "$APP"
mkdir -p "$APP/Contents/MacOS" "$APP/Contents/Resources"

# --- Icon: icon.png -> red.icns (all standard sizes) ---
ICONSET="$(mktemp -d)/red.iconset"
mkdir -p "$ICONSET"
for sz in 16 32 128 256 512; do
  sips -z "$sz" "$sz"          "$ICON_SRC" --out "$ICONSET/icon_${sz}x${sz}.png"      >/dev/null
  sips -z $((sz*2)) $((sz*2))  "$ICON_SRC" --out "$ICONSET/icon_${sz}x${sz}@2x.png"   >/dev/null
done
iconutil -c icns "$ICONSET" -o "$APP/Contents/Resources/red.icns"
rm -rf "$(dirname "$ICONSET")"

# --- Launcher: cd into release/ and exec the live binary (parity with terminal) ---
cat > "$APP/Contents/MacOS/red" <<EOF
#!/bin/bash
# Auto-generated by make_mac_app.sh — launches the live build.
BIN="$BIN"
cd "\$(dirname "\$BIN")" || exit 1
exec "\$BIN" "\$@"
EOF
chmod +x "$APP/Contents/MacOS/red"

# --- Info.plist ---
cat > "$APP/Contents/Info.plist" <<'EOF'
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleName</key>              <string>Red</string>
    <key>CFBundleDisplayName</key>       <string>Red</string>
    <key>CFBundleExecutable</key>        <string>red</string>
    <key>CFBundleIconFile</key>          <string>red.icns</string>
    <key>CFBundleIdentifier</key>        <string>com.red.app</string>
    <key>CFBundlePackageType</key>       <string>APPL</string>
    <key>CFBundleShortVersionString</key><string>1.0</string>
    <key>CFBundleVersion</key>           <string>1</string>
    <key>LSMinimumSystemVersion</key>    <string>13.0</string>
    <key>NSHighResolutionCapable</key>   <true/>
</dict>
</plist>
EOF

plutil -lint "$APP/Contents/Info.plist" >/dev/null

# Refresh LaunchServices so the icon/metadata pick up immediately.
touch "$APP"
/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister \
  -f "$APP" 2>/dev/null || true

echo "[✔] $APP created."
echo "    Double-click it (or drag to the Dock). It launches: $BIN"
echo "    Rebuild any time with: cmake --build \"$SRC_DIR/release\" -j  (the icon follows the live build)."
