#!/usr/bin/env python3
"""Generate a calibration post target for the rainbow rig.

Produces, in scripts/post_target/:
  - posts_layout.csv   (x_mm, y_mm, tip_z_mm per post, id = row order)
  - post_target.scad   (OpenSCAD source; render + export STL to print)

Design rules (see the cropped-sensor calibration workflow):
  - Post 3D positions are TRIANGULATED with the stage-1 calibration, so the
    print does NOT need to be dimensionally accurate — only rigid during a
    session, with identifiable, well-distributed tips.
  - Tips get unique heights; heights follow the arena's clearance envelope
    (arch: tall in the center, falling off toward the ends).
  - Posts are ordered left-to-right along the base so the click order is
    obvious in every camera view.

Edit the parameters below and re-run. All units mm.
"""

import csv
import math
import os
import random

# ── Arena / target parameters ────────────────────────────────────────────────
BASE_L = 495.0       # base length  (19.5 in)
BASE_W = 50.0        # base width   (2 in)
BASE_T = 5.0         # base plate thickness
MARGIN_X = 12.0      # keep posts this far from the ends
MARGIN_Y = 8.0       # keep posts this far from the sides

N_POSTS = 36

# Clearance envelope along the length (the "rainbow" arch).
# Parabolic by default: CLEAR_CENTER at mid-length, CLEAR_END at the ends.
CLEAR_CENTER = 57.0  # ~2.25 in of the quoted 2-3 in center clearance
CLEAR_END = 15.0     # clearance near the outer edges ("falls off fast")
ENVELOPE_POWER = 2.0 # 2 = parabola; raise for a flatter middle/faster falloff

# Posts occupy this fraction band of the local clearance
H_FRAC_LO, H_FRAC_HI = 0.20, 0.80
H_MIN = 6.0          # never shorter than this (clickable above the base)

POST_D = 5.0         # post shaft diameter
TIP_H = 4.0          # conical tip height (click the apex)
SEED = 7             # layout is deterministic

# Split into print-bed-sized sections: also emits one
# post_target_section<i>.scad per section (base cut at section boundaries,
# geometry translated to the origin). Posts keep their global position and id.
# Set to 1 to disable. Sections butt together edge-to-edge when mounted;
# alignment does not need to be precise (post 3D is triangulated, not CAD).
SECTIONS = 3

# ─────────────────────────────────────────────────────────────────────────────

def clearance(x: float) -> float:
    """Arch clearance envelope at position x along the base."""
    t = abs(2.0 * x / BASE_L - 1.0)  # 0 at center, 1 at ends
    return CLEAR_END + (CLEAR_CENTER - CLEAR_END) * (1.0 - t ** ENVELOPE_POWER)


def make_layout():
    rng = random.Random(SEED)
    usable_l = BASE_L - 2 * MARGIN_X
    slot = usable_l / N_POSTS

    # Shuffled height fractions -> unique, well-spread heights
    fracs = [H_FRAC_LO + (H_FRAC_HI - H_FRAC_LO) * i / (N_POSTS - 1)
             for i in range(N_POSTS)]
    rng.shuffle(fracs)

    posts = []
    prev_y = None
    for i in range(N_POSTS):
        x = MARGIN_X + (i + 0.5) * slot + rng.uniform(-0.25, 0.25) * slot
        # scatter across the width, avoiding a straight line and keeping
        # consecutive posts separated in y so they don't occlude each other
        while True:
            y = rng.uniform(MARGIN_Y, BASE_W - MARGIN_Y)
            if prev_y is None or abs(y - prev_y) > (BASE_W - 2 * MARGIN_Y) / 4:
                break
        prev_y = y
        h = max(H_MIN, fracs[i] * clearance(x))
        h = round(h * 2) / 2  # 0.5 mm steps
        posts.append((round(x, 1), round(y, 1), h))

    # enforce unique heights (identifiability)
    seen = set()
    fixed = []
    for x, y, h in posts:
        while h in seen:
            h += 0.5
        seen.add(h)
        fixed.append((x, y, h))
    return fixed


def write_csv(posts, path):
    with open(path, "w", newline="") as f:
        w = csv.writer(f)
        w.writerow(["id", "x_mm", "y_mm", "tip_z_mm"])
        for i, (x, y, h) in enumerate(posts):
            w.writerow([i, x, y, h])


def write_scad(posts, path, base_l=None, x_shift=0.0, note=""):
    """Write a scad for the given posts on a base of length base_l,
    translating all geometry by -x_shift (sections start at the origin)."""
    if base_l is None:
        base_l = BASE_L
    lines = [
        "// Auto-generated by scripts/generate_post_target.py — edit that, not this.",
    ]
    if note:
        lines.append("// " + note)
    lines += [
        f"base_l = {base_l}; base_w = {BASE_W}; base_t = {BASE_T};",
        f"post_d = {POST_D}; tip_h = {TIP_H};",
        "$fn = 48;",
        "",
        "// [x, y, tip_height] per post (tip apex sits at z = tip_height)",
        "posts = [",
    ]
    for x, y, h in posts:
        lines.append(f"  [{round(x - x_shift, 1)}, {y}, {h}],")
    lines += [
        "];",
        "",
        "module post(x, y, h) {",
        "  translate([x, y, 0]) {",
        "    cylinder(h = max(0.1, h - tip_h), d = post_d);",
        "    translate([0, 0, max(0.1, h - tip_h)])",
        "      cylinder(h = tip_h, d1 = post_d, d2 = 0.4);  // clickable apex",
        "  }",
        "}",
        "",
        "translate([0, 0, -base_t]) cube([base_l, base_w, base_t]);",
        "for (p = posts) post(p[0], p[1], p[2]);",
        "",
        "// Section alignment does NOT need to be precise: post 3D positions",
        "// are triangulated with the stage-1 calibration, not taken from CAD.",
    ]
    with open(path, "w") as f:
        f.write("\n".join(lines) + "\n")


def main():
    out_dir = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                           "post_target")
    os.makedirs(out_dir, exist_ok=True)
    posts = make_layout()
    write_csv(posts, os.path.join(out_dir, "posts_layout.csv"))
    write_scad(posts, os.path.join(out_dir, "post_target.scad"))

    if SECTIONS > 1:
        sec_l = BASE_L / SECTIONS
        for s in range(SECTIONS):
            x0 = s * sec_l
            sec_posts = [p for p in posts if x0 <= p[0] < x0 + sec_l]
            ids = [i for i, p in enumerate(posts) if x0 <= p[0] < x0 + sec_l]
            note = (f"Section {s + 1}/{SECTIONS}: global posts "
                    f"{ids[0]}-{ids[-1]}, arena x {x0:.0f}-{x0 + sec_l:.0f} mm"
                    if ids else f"Section {s + 1}/{SECTIONS}: no posts")
            write_scad(sec_posts,
                       os.path.join(out_dir, f"post_target_section{s + 1}.scad"),
                       base_l=sec_l, x_shift=x0, note=note)
            print(note)

    print(f"{len(posts)} posts -> {out_dir}")
    print(f"{'id':>3} {'x_mm':>7} {'y_mm':>6} {'tip_mm':>7}  {'clearance':>9}")
    for i, (x, y, h) in enumerate(posts):
        print(f"{i:>3} {x:>7.1f} {y:>6.1f} {h:>7.1f}  {clearance(x):>9.1f}")
    hs = [h for _, _, h in posts]
    print(f"heights: {min(hs):.1f}-{max(hs):.1f} mm, all unique: "
          f"{len(set(hs)) == len(hs)}")


if __name__ == "__main__":
    main()
