# Homebrew formula for RED — GPU-accelerated multi-camera keypoint labeling.
#
# This formula lives in the tap repository at:
#   https://github.com/JohnsonLabJanelia/homebrew-red
#
# Installation:
#   brew tap JohnsonLabJanelia/red
#   brew install red                    # stable release
#   brew install --HEAD red             # latest main branch

class Red < Formula
  desc "GPU-accelerated multi-camera 3D keypoint labeling tool"
  homepage "https://github.com/JohnsonLabJanelia/red"
  license "MIT"

  # ---------------------------------------------------------------------------
  # Stable release (update url + sha256 after each tagged release)
  # ---------------------------------------------------------------------------
  # The source tarball is generated by the release workflow at
  # .github/workflows/release.yml — it is a "fat" archive that includes all
  # submodule contents so Homebrew does not need network access during install.
  #
  # After tagging v1.0.0:
  #   1. Push the tag: git push origin v1.0.0
  #   2. GitHub Actions builds and uploads red-v1.0.0-src.tar.gz
  #   3. Copy the SHA256 from the Actions log into sha256 below
  #   4. Set url to the release download URL
  #
  # url "https://github.com/JohnsonLabJanelia/red/releases/download/v1.0.0/red-v1.0.0-src.tar.gz"
  # sha256 "REPLACE_WITH_SHA256_FROM_RELEASE_WORKFLOW"

  # ---------------------------------------------------------------------------
  # HEAD install — builds from the latest main branch.
  # Use while a stable release is not yet tagged, or for development:
  #   brew install --HEAD JohnsonLabJanelia/red/red
  # ---------------------------------------------------------------------------
  head "https://github.com/JohnsonLabJanelia/red.git", branch: "rob_dev_metal"

  # Build dependencies (not needed at runtime)
  depends_on "cmake"      => :build
  depends_on "pkg-config" => :build

  # Runtime dependencies (Homebrew handles installation automatically)
  depends_on "ffmpeg"
  depends_on "glfw"
  depends_on "opencv"  # includes opencv_sfm via contrib modules

  # Needs Xcode command-line tools for Metal headers and ObjC++ compiler
  uses_from_macos "xcode" => :build

  # macOS 12+ required (Metal compute shaders + VideoToolbox async decode)
  depends_on macos: :monterey

  def install
    # For HEAD installs the repo is cloned without --recursive.
    # Fetch all submodules (imgui, implot, ImGuiFileDialog, etc.) now.
    # For versioned installs from the fat tarball this is a no-op because
    # the submodule directories are already present.
    if build.head?
      system "git", "submodule", "update", "--init", "--recursive"
    end

    # Pass the Homebrew prefix explicitly so CMakeLists.txt does not fall
    # back to /opt/homebrew (which would break on Intel Macs at /usr/local).
    args = %W[
      -DHOMEBREW_PREFIX=#{HOMEBREW_PREFIX}
      -DCMAKE_PREFIX_PATH=#{HOMEBREW_PREFIX}
    ]

    system "cmake", "-S", ".", "-B", "build", *args, *std_cmake_args
    system "cmake", "--build", "build", "--config", "Release",
           "-j#{ENV.make_jobs}"

    bin.install "build/red"

    # Install fonts required at runtime (the app looks for them relative to
    # the executable or in standard system locations).
    (share/"red/fonts").install Dir["fonts/*"]
  end

  def caveats
    <<~EOS
      RED requires a project file (.redproj) and calibration YAML files.
      See the user guide for setup instructions:
        https://github.com/JohnsonLabJanelia/red/blob/main/USER_GUIDE.md

      On first launch macOS Gatekeeper may show a security warning.
      If so, open System Settings → Privacy & Security → Allow Anyway,
      or run once:
        xattr -dr com.apple.quarantine #{bin}/red
    EOS
  end

  test do
    # Verify the binary is present and executable
    assert_predicate bin/"red", :exist?
    assert_predicate bin/"red", :executable?
    # The application needs a display to start; check it at least exits
    # with a recognisable error rather than crashing silently.
    output = shell_output("#{bin}/red 2>&1", 1)
    assert_match(/red|project|usage/i, output)
  end
end
