// Auto-generated by scripts/generate_post_target.py — edit that, not this.
base_l = 495.0; base_w = 50.0; base_t = 5.0;
post_d = 5.0; tip_h = 4.0;
$fn = 48;

// [x, y, tip_height] per post (tip apex sits at z = tip_height)
posts = [
  [16.2, 12.0, 15.0],
  [30.4, 35.7, 15.5],
  [42.6, 20.7, 10.5],
  [58.1, 10.1, 9.5],
  [68.0, 31.1, 24.5],
  [83.5, 18.7, 25.5],
  [97.6, 35.0, 14.0],
  [111.4, 16.3, 26.5],
  [123.7, 25.9, 20.5],
  [138.7, 41.3, 20.0],
  [146.9, 22.2, 34.0],
  [164.1, 13.2, 30.0],
  [175.5, 30.7, 42.0],
  [190.4, 18.7, 25.0],
  [203.0, 28.2, 11.0],
  [215.3, 40.1, 29.5],
  [227.7, 30.6, 40.5],
  [238.1, 41.8, 18.0],
  [256.1, 17.7, 32.0],
  [266.4, 30.7, 45.5],
  [277.1, 13.7, 24.0],
  [290.8, 34.1, 13.0],
  [304.0, 16.4, 42.5],
  [318.7, 37.6, 16.0],
  [329.8, 23.3, 26.0],
  [345.9, 38.0, 11.5],
  [360.8, 17.5, 27.0],
  [371.2, 38.1, 18.5],
  [387.9, 13.1, 32.5],
  [395.8, 24.5, 21.0],
  [411.6, 8.1, 27.5],
  [423.6, 20.6, 10.0],
  [437.6, 40.4, 8.0],
  [451.5, 25.5, 19.0],
  [464.1, 9.8, 9.0],
  [479.1, 34.5, 12.0],
];

module post(x, y, h) {
  translate([x, y, 0]) {
    cylinder(h = max(0.1, h - tip_h), d = post_d);
    translate([0, 0, max(0.1, h - tip_h)])
      cylinder(h = tip_h, d1 = post_d, d2 = 0.4);  // clickable apex
  }
}

translate([0, 0, -base_t]) cube([base_l, base_w, base_t]);
for (p = posts) post(p[0], p[1], p[2]);

// Section alignment does NOT need to be precise: post 3D positions
// are triangulated with the stage-1 calibration, not taken from CAD.
