// Auto-generated by scripts/generate_post_target.py — edit that, not this.
// Section 1/3: global posts 0-11, arena x 0-165 mm
base_l = 165.0; base_w = 50.0; base_t = 5.0;
post_d = 5.0; tip_h = 4.0;
$fn = 48;

// [x, y, tip_height] per post (tip apex sits at z = tip_height)
posts = [
  [16.2, 12.0, 15.0],
  [30.4, 35.7, 15.5],
  [42.6, 20.7, 10.5],
  [58.1, 10.1, 9.5],
  [68.0, 31.1, 24.5],
  [83.5, 18.7, 25.5],
  [97.6, 35.0, 14.0],
  [111.4, 16.3, 26.5],
  [123.7, 25.9, 20.5],
  [138.7, 41.3, 20.0],
  [146.9, 22.2, 34.0],
  [164.1, 13.2, 30.0],
];

module post(x, y, h) {
  translate([x, y, 0]) {
    cylinder(h = max(0.1, h - tip_h), d = post_d);
    translate([0, 0, max(0.1, h - tip_h)])
      cylinder(h = tip_h, d1 = post_d, d2 = 0.4);  // clickable apex
  }
}

translate([0, 0, -base_t]) cube([base_l, base_w, base_t]);
for (p = posts) post(p[0], p[1], p[2]);

// Section alignment does NOT need to be precise: post 3D positions
// are triangulated with the stage-1 calibration, not taken from CAD.
