// Auto-generated by scripts/generate_post_target.py — edit that, not this.
// Section 3/3: global posts 25-35, arena x 330-495 mm
base_l = 165.0; base_w = 50.0; base_t = 5.0;
post_d = 5.0; tip_h = 4.0;
$fn = 48;

// [x, y, tip_height] per post (tip apex sits at z = tip_height)
posts = [
  [15.9, 38.0, 11.5],
  [30.8, 17.5, 27.0],
  [41.2, 38.1, 18.5],
  [57.9, 13.1, 32.5],
  [65.8, 24.5, 21.0],
  [81.6, 8.1, 27.5],
  [93.6, 20.6, 10.0],
  [107.6, 40.4, 8.0],
  [121.5, 25.5, 19.0],
  [134.1, 9.8, 9.0],
  [149.1, 34.5, 12.0],
];

module post(x, y, h) {
  translate([x, y, 0]) {
    cylinder(h = max(0.1, h - tip_h), d = post_d);
    translate([0, 0, max(0.1, h - tip_h)])
      cylinder(h = tip_h, d1 = post_d, d2 = 0.4);  // clickable apex
  }
}

translate([0, 0, -base_t]) cube([base_l, base_w, base_t]);
for (p = posts) post(p[0], p[1], p[2]);

// Section alignment does NOT need to be precise: post 3D positions
// are triangulated with the stage-1 calibration, not taken from CAD.
