// Auto-generated by scripts/generate_post_target.py — edit that, not this.
// Section 2/3: global posts 12-24, arena x 165-330 mm
base_l = 165.0; base_w = 50.0; base_t = 5.0;
post_d = 5.0; tip_h = 4.0;
$fn = 48;

// [x, y, tip_height] per post (tip apex sits at z = tip_height)
posts = [
  [10.5, 30.7, 42.0],
  [25.4, 18.7, 25.0],
  [38.0, 28.2, 11.0],
  [50.3, 40.1, 29.5],
  [62.7, 30.6, 40.5],
  [73.1, 41.8, 18.0],
  [91.1, 17.7, 32.0],
  [101.4, 30.7, 45.5],
  [112.1, 13.7, 24.0],
  [125.8, 34.1, 13.0],
  [139.0, 16.4, 42.5],
  [153.7, 37.6, 16.0],
  [164.8, 23.3, 26.0],
];

module post(x, y, h) {
  translate([x, y, 0]) {
    cylinder(h = max(0.1, h - tip_h), d = post_d);
    translate([0, 0, max(0.1, h - tip_h)])
      cylinder(h = tip_h, d1 = post_d, d2 = 0.4);  // clickable apex
  }
}

translate([0, 0, -base_t]) cube([base_l, base_w, base_t]);
for (p = posts) post(p[0], p[1], p[2]);

// Section alignment does NOT need to be precise: post 3D positions
// are triangulated with the stage-1 calibration, not taken from CAD.
